const commander = require('commander')

module.exports.commander = commander

commander.version('1.0.0')
  .option('-G, --getToken', 'Get the token user by your default browser')
  .option('-S, --setToken [TOKEN]', 'Set the user token')
  .option('-o, --offline', 'To post data offline')
  .option('-P, --push', 'To syncro datas set offline on Trello')
  .option('-L, --listing', 'Action of listing')
  .option('-A, --adding', 'Action of adding')
  .option('-M, --moving', 'Action of moving (for a card ONLY)')
  .option('-t, --to [DESTINATION_LIST_NAME]', 'a destination list (for moving)')
  .option('-b, --board [BOARD_NAME]', 'Action on a board')
  .option('-l, --list [LIST_NAME]', 'Action on a list')
  .option('-c, --card [CARD_NAME]', 'Action on a card')
  .on('--help', function(){
    console.log('  Examples:')
    console.log('')
    console.log('   # Listing Online')
    console.log('')
    console.log('    $ trelloken -Lb')
    console.log('        This will list all your boards')
    console.log('')
    console.log('    $ trelloken -b [BOARD_NAME] -Ll')
    console.log('        This will list all your lists of an existing board.')
    console.log('')
    console.log('    $ trelloken -b [BOARD_NAME] -l [LIST_NAME] -Lc')
    console.log('        This will list all your card of your existing list of your existing board.')
    console.log('')
    console.log('   # Adding Online (same for offline but add -o)')
    console.log('')
    console.log('    $ trelloken -Ab [BOARD_NAME]')
    console.log('        This will add a board.')
    console.log('')
    console.log('    $ trelloken -b [BOARD_NAME] -Al [LIST_NAME]')
    console.log('        This will add a list in a board.')
    console.log('')
    console.log('    $ trelloken -b [BOARD_NAME] -l [LIST_NAME] -Ac [CARD_NAME]')
    console.log('        This will add a card in a list in a board.')
    console.log('')
    console.log('   # Moving Online')
    console.log('')
    console.log('    $ trelloken -b [BOARD_NAME] -l [LIST_NAME] -Mc [CARD_NAME] -t [DESTINATION_LIST_NAME]')
    console.log('        This will add a card in a list in a board.')
    console.log('')
    console.log('  Notes:')
    console.log('')
    console.log('    If your parameter contain space, write it between quote : "some board"')
    console.log('')
    console.log('    You can specify [parameters] in the command, otherwise there will be asked')
    console.log('')
  })

commander.parse(process.argv)
